# Generated by Django 4.2.6 on 2023-12-01 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_task_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
