# Generated by Django 4.2.6 on 2023-12-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_tarea'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Trabajo',
        ),
    ]
