# Generated by Django 4.2.6 on 2023-12-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_project_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
